export const PLANS_DATA = [
  {
    id: "essential",
    name: "Essential",
    tagline: "1 Task at a Time",
    price: "$2,600",
    description: "Perfect for validating your idea and getting initial feedback",
    subtitle: "Quick validation of your concept with essential features and feedback",
    features: [
      "Basic UI/UX Design",
      "Core Functionality Testing",
      "Performance Analysis",
      "Security Assessment",
      "User Feedback Collection",
      "Basic Documentation",
    ],
    highlights: ["Quick validation", "Essential features", "Rapid feedback"],
    popular: false,
    color: "blue",
  },
  {
    id: "growth",
    name: "Growth",
    tagline: "2 Tasks at a Time",
    price: "$5,200",
    description: "Ideal for rapid development and quick market entry",
    subtitle: "Fast-track your project with comprehensive development and support",
    features: [
      "Advanced UI/UX Design",
      "Full Feature Development",
      "Performance Optimization",
      "Security Implementation",
      "User Testing & Feedback",
      "Comprehensive Documentation",
      "Deployment Support",
      "2 Weeks of Maintenance",
      "All in testing",
    ],
    highlights: ["Fast development", "Complete solution", "Market ready"],
    popular: true,
    color: "purple",
  },
  {
    id: "enterprise",
    name: "Enterprise Plan",
    tagline: "Dedicated Support",
    price: "Custom",
    description: "Tailored solution for complex business needs",
    subtitle: "Enterprise-grade solutions with dedicated support and customization",
    features: [
      "Custom UI/UX Design",
      "Full-Scale Development",
      "Advanced Security Features",
      "Scalability Planning",
      "Enterprise Integration",
      "24/7 Support",
      "Custom Maintenance Plan",
      "Dedicated Project Manager",
    ],
    highlights: ["Enterprise grade", "Fully customizable", "Dedicated support"],
    popular: false,
    color: "green",
  },
];

export const FUNNEL_QUESTIONS = [
  {
    id: "team_size",
    question: "What's the size of your team?",
    type: "slider",
    min: 1,
    max: 50,
    step: 1,
    labels: ["1", "10", "20", "30", "40", "50+"],
  },
  {
    id: "project_complexity",
    question: "How would you describe your project?",
    options: [
      {
        value: "validation",
        label: "Concept validation & testing",
        icon: "HiMiniViewfinderCircle",
        description: "Test your idea with core features and user feedback",
      },
      {
        value: "development",
        label: "Full development & launch",
        icon: "HiOutlineRocketLaunch",
        description: "Build and launch a complete solution ready for market",
      },
      {
        value: "enterprise",
        label: "Enterprise-scale solution",
        icon: "HiOutlineBuildingOffice",
        description: "Complex system with custom integrations and enterprise features",
      },
    ],
  },
  {
    id: "budget",
    question: "What's your budget range?",
    options: [
      {
        value: "essential",
        label: "Under $3,000",
        icon: "HiOutlineCurrencyDollar",
        description: "Perfect for validating concepts and essential features",
      },
      {
        value: "growth",
        label: "$3,000 - $6,000",
        icon: "HiOutlineBanknotes",
        description: "Comprehensive development with faster execution",
      },
      {
        value: "premium",
        label: "$6,000 - $15,000",
        icon: "HiOutlineCreditCard",
        description: "Advanced features with priority support",
      },
      {
        value: "enterprise",
        label: "$15,000+",
        icon: "HiOutlineBuildingLibrary",
        description: "Custom solutions with dedicated project management",
      },
    ],
  },
  {
    id: "timeline",
    question: "What's your preferred timeline?",
    options: [
      {
        value: "urgent",
        label: "ASAP (< 4 weeks)",
        icon: "HiOutlineBolt",
        description: "Need quick validation or immediate results",
      },
      {
        value: "standard",
        label: "1-3 months",
        icon: "HiOutlineCalendar",
        description: "Standard development timeline for most projects",
      },
      {
        value: "planned",
        label: "3+ months",
        icon: "HiOutlineCalendarDays",
        description: "Long-term project with comprehensive planning",
      },
      {
        value: "flexible",
        label: "Flexible timeline",
        icon: "HiOutlineArrowPath",
        description: "No strict deadlines, quality over speed",
      },
    ],
  },
  {
    id: "support_level",
    question: "What level of support do you need?",
    options: [
      {
        value: "basic",
        label: "Basic documentation & guidance",
        icon: "HiOutlineDocument",
        description: "Essential documentation and basic guidance",
      },
      {
        value: "standard",
        label: "Regular check-ins & support",
        icon: "HiOutlineChatBubbleLeft",
        description: "Regular communication and standard support",
      },
      {
        value: "premium",
        label: "Priority support & maintenance",
        icon: "HiOutlineStar",
        description: "Fast response times and ongoing maintenance",
      },
      {
        value: "dedicated",
        label: "Dedicated project manager",
        icon: "HiOutlineHandThumbUp",
        description: "Personal project manager for enterprise needs",
      },
    ],
  },
];